version: '3'
services:
  db:
    build: ./docker/mysql
    env_file:
      - .env
    volumes:
      - ${DATA_PATH_HOST}:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"
    user: "1000:50"

  app:
    build: ./docker/ruby
    env_file:
      - .env
    volumes:
      - ${APP_CODE_PATH_HOST}:/srv
      - bundle:/usr/local/bundle
      - puma_shared:/puma_shared
    ports:
      - "${RAILS_PORT}:3000"
    depends_on:
      - db

  web:
    build: ./docker/nginx
    env_file:
      - .env
    volumes:
      - ${APP_CODE_PATH_HOST}:/srv
      - puma_shared:/puma_shared
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
    depends_on:
      - app

volumes:
  bundle: {}
  puma_shared: {}