version: '3'
services:
  db:
    build: ./mysql
    env_file:
      - .env
    volumes:
      - ./tmp/db:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"
    user: "1000:50"

  app:
    build: .
    env_file:
      - .env
    volumes:
      - .:/myapp
      - bundle:/usr/local/bundle
      - public_data:/myapp/public
      - tmp_data:/myapp/tmp
      - log_data:/myapp/log
    ports:
      - "${RAILS_PORT}:3000"
    depends_on:
      - db

  web:
    build: ./nginx
    env_file:
      - .env
    volumes:
      - public_data:/myapp/public
      - tmp_data:/myapp/tmp
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
    depends_on:
      - app

volumes:
  bundle: {}
  public_data: {}
  tmp_data: {}
  log_data: {}