version: '3'
services:
  db:
    build: ./mysql
    env_file:
      - .env
    volumes:
      - ./tmp/db:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"
    user: "1000:50"

  app:
    build: .
    env_file:
      - .env
    command: bundle exec puma -C config/puma.rb
    #command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
      - public-data:/myapp/public
      - bundle:/usr/local/bundle
      - tmp-data:/myapp/tmp
      - log-data:/myapp/log
    ports:
      - "${RAILS_PORT}:3000"
    depends_on:
      - db

  web:
    build: ./nginx
    volumes:
      - public-data:/myapp/public
      - tmp-data:/myapp/tmp
    ports:
      - 80:80
    depends_on:
      - app

volumes:
  public-data: {}
  tmp-data: {}
  log-data: {}
  bundle: {}