version: '3'
services:
  db:
    build: ./mysql
    env_file:
      - .env
    volumes:
      - ./tmp/db:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"
    user: "1000:50"

  web:
    build: .
    env_file:
      - .env
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
      - bundle:/usr/local/bundle
    ports:
      - "${RAILS_PORT}:3000"
    depends_on:
      - db

volumes:
  bundle: {}